spring:
  application:
    name: rabbitmqchat
  rabbitmq:
    username: ohj4312
    password: Asdf1234$
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 1


logging:
  level:
    org: ERROR